### ISSUE TITLE
Fix: Storybook Docs fail with error "Cannot read properties of undefined (reading 'content')"

### ISSUE THREAD

**Issue by andreaforni** [nearform/quantum#317]
In the [deployed Storybook instance](https://nearform.github.io/quantum/?path=/docs/components-accordion--docx), the `Docx` pages are failing with this error: 

```
Cannot read properties of undefined (reading 'content')
TypeError: Cannot read properties of undefined (reading 'content')
    at https://nearform.github.io/quantum/assets/index-463bac67.js:408:3731
    at handleInterpolation (https://nearform.github.io/quantum/assets/index-463bac67.js:360:2754)
    at serializeStyles (https://nearform.github.io/quantum/assets/index-463bac67.js:365:1292)
    at https://nearform.github.io/quantum/assets/index-463bac67.js:369:972
    at https://nearform.github.io/quantum/assets/index-463bac67.js:365:2381
    at eu (https://nearform.github.io/quantum/assets/index-add592e3.js:22:19476)
    at oo (https://nearform.github.io/quantum/assets/index-add592e3.js:24:1571)
    at ka (https://nearform.github.io/quantum/assets/index-add592e3.js:24:45660)
    at ya (https://nearform.github.io/quantum/assets/index-add592e3.js:24:39496)
    at wf (https://nearform.github.io/quantum/assets/index-add592e3.js:24:39427)
```
Opening the `quantum/assets/index-463bac67.js:408:3731`the error is here:

```JavaScript
var prism_light_default = SyntaxHighlighter
  , Container$1 = newStyled.div(({theme: t})=>({
    position: "absolute",
    bottom: 0,
    right: 0,
    maxWidth: "100%",
    display: "flex",
    background: t.background.content, // <- HERE!
    zIndex: 1
}))
```

**Comment by simoneb** [comment]
I've seen this happen before more than a few times (I mean within this same application). Since having this regression continuously doesn't look very good, can we please see if we can put in place something which can detect this issue and fails the build? I'm not sure if it is possible and how much work it would be, but I think it's worth a try
